### ISSUE TITLE
Boosting not working 9/10 times

### ISSUE THREAD

**Issue by usselman** [pow-co/powco-webui-react#80]
I tried to boost over 10 links today and only one or two of them seemed to take. I tried multiple times with many of them. It would say boost error, and sometimes it would error over and over and then randomly say success.

**Comment by derrickhorton** [comment]
> I tried to boost over 10 links today and only one or two of them seemed to take. I tried multiple times with many of them. It would say boost error, and sometimes it would error over and over and then randomly say success.

Yeah! Same. 

What's with that? Anyone know the cause? 

It's not like every time I use relayx it takes ten tries before something works.

**Comment by 1aristotelis** [comment]
boosting is much more reliable with new pow.co frontend don't you think ?

**Comment by 1aristotelis** [comment]
I just have 2 consecutive errors when boosting. Here is what I found in my browser console
`
{
    "message": "Request failed with status code 500",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 500\n    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:24:12)\n    at XMLHttpRequest.onloadend (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:117:66)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json"
        },
        "method": "post",
        "url": "https://pow.co/api/v1/boost/jobs",
        "data": "{\"transaction\":\"010000000155e92b86bb5c4a74819d867628b4ba5961f31278bf7606419dc454b20b6ec8e5020000006a473044022051bfbe4ed1fb74b1cb24daa4359eda3fc7f04222c8e7ad81b9b68b9525be913f0220376328a6331d55edfcef272f158f48c452eff00ac55130acf79cdab78ee282e54121030a094087daa4ff59e49112688a3054670ecdcea3c80eb8b81a4676adcf2cd8e0ffffffff034e0c010000000000b308626f6f7374706f7775040000000020a23f026af431b03daa5dfd547031b74f68801b5264d60fc96d94457bee96758a04f0de2d1d066d61726b657404cd0bf0d2007e7c557a766b7e52796b557a8254887e557a8258887e7c7eaa7c6b7e7e7c8254887e6c7e7c8254887eaa01007e816c825488537f7681530121a5696b768100a0691d00000000000000000000000000000000000000000000000000000000007e6c539458959901007e819f6976a96c88ac00000000000000002f006a2231487948587459577947655072485669736e4e645339333156743643716f7555795a0972656c6179782e696fb8b10000000000001976a914d8c851f9fcc01c53f6c6e62e259b065d2b85b9d688ac00000000\"}"
    },
    "code": "ERR_BAD_RESPONSE",
    "status": 500
}
`

**Comment by usselman** [comment]
It is still really inconsistent for me, strong majority error than success

**Comment by usselman** [comment]
I have confirmed basically the same error relating to my jobs. I tried to boost a club posting today maybe 35 times and only got success once, though I am pretty sure my bitcoin was spent for each one. 

Btw @GuiDeMa I do love the new pow.co , it looks great.

**Comment by usselman** [comment]
I can confirm that boosting is working much better today, so I will close the issue.

**Comment by derrickhorton** [comment]
Awesome! I am so glad to see this!
